wafflestudio/snutt-ev-web

- .github/workflows/build.yml
- .github/workflows/cd.yml
- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-prod.yml
- package.json
S3 업로드 -> 연결된 Cloudfront invalidation
main, dev 브랜치 각각에서 prod, dev 배포 돌게 만들었고, CI가 끝나고 CD 돌게 했습니다
> CD [SNUTT-285]

- lib/components/CollapsableText/index.tsx
- pageImpl/detailImpl/__components__/LectureReviewCard.tsx
- pageImpl/mainImpl/__components__/ReviewCard.tsx
- pageImpl/mainImpl/index.tsx
- pages/_app.tsx
> add CollapsableText component, apply to main and detail

- lib/components/Appbar/index.tsx
- pages/_app.tsx
meta tag를 추가하여 모바일에서 zoom scale 되는 것을 방지
> Scale issue [SNUTT-301]

- pageImpl/mainImpl/__components__/RecentCarousel.tsx
- pages/_app.tsx
- max width 768px로 변경
- carousel style 수정
> Fix style (max width, carousel width)

- lib/api/request.ts
> TAG SEARCH (#62)

- .env.production
- pages/index.tsx
api url prod 버전 진짜 prod로 고치고, 페이지 /, /main 둘다 main page 틀게 했어요
> Fix api url

- pageImpl/createImpl/index.tsx
window.alert를 mui Dialog로 변경했어요.
post 후 router.push에 오타가 있어서 수정했습니다. 이제 포스팅된 후 디테일로 잘 이동합니다.
> Fix validation alert with modal & Fix typo

- pageImpl/detailImpl/__containers__/useLectureEvaluationsContainer.tsx
- pageImpl/detailImpl/index.tsx
- pageImpl/mainImpl/index.tsx
디테일 뷰에서 버튼이 안눌리는 이유는 pagination에서 무한 렌더를 일으켰기 때문이였다고 한다... @sanggggg 는 빠따 맞을 준비를 하라
> fix detail view infinite re-render

- pageImpl/createImpl/index.tsx
- pageImpl/detailImpl/index.tsx
1. CREATE -> DETAIL 에서 CREATE 가는 문제 해결
2. DETAIL 이 initial로 (url로) 로드됐을 때 back 기능 설정
> Router 이슈 해결 [SNUTT-369, SNUTT-368]

- pageImpl/createImpl/__components__/EvalPolygon.tsx
- pageImpl/createImpl/__components__/ToolTipContent.tsx
- pageImpl/detailImpl/index.tsx
수도 엘리먼트와 z-index 설정하는 것이 정확히 되지 않는 이슈가 있어서 걍 div로 분리했습니다
> Fix tooltip

- lib/components/Miscellaneous/EmptyReviewPlaceholder.tsx
- lib/components/Miscellaneous/Loading.tsx
- pageImpl/detailImpl/__components__/LectureReviewCard.tsx
- pageImpl/detailImpl/index.tsx
- pageImpl/mainImpl/index.tsx
- pageImpl/searchImpl/index.tsx
- MUI의 로딩 동그라미 사용해서 페이지네이션 뚝뚝 끊기는 느낌 해결
- 검색뷰 무한 리렌더로 인해 버튼 클릭 안되는 이슈 해결
- 메인뷰 하단 강의목록 비었을때 고양이 추가
- 오타 수정
> [SNUTT-337, SNUTT-374, SNUTT-390] 강의(평) 리스트 관련 UI/버그 수정

- lib/styles/colors.ts
- package.json
- pageImpl/mailVerifyImpl/index.tsx
- pages/mailVerify/index.tsx
- yarn.lock
> Implement mailVerify view UI

- lib/components/Icons/SvgWarning.tsx
- lib/styles/colors.ts
- pageImpl/createImpl/__components__/EvalBasic.tsx
- pageImpl/createImpl/index.tsx
> 강의평 등록 시 30자 이상이도록

- README.md
from https://wafflestudio.slack.com/archives/C0PAVPS5T/p1661867938070419?thread_ts=1661866767.799919&cid=C0PAVPS5T
> :technologist: fix README env key

- README.md
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1662812907822019?thread_ts=1662723933.611569&cid=C0PAVPS5T
> :memo: 리드미 api url 업데이트

- .eslintrc
- lib/api/request.ts
- lib/components/Rating/index.tsx
> :adhesive_bandage: var 제거하고 let 또는 const 로 변경

- lib/api/apis.ts
> :recycle: 최근 학기 목록 불러오는 api SnuttApi -> evClient 마이그레이션

- .env.dev
- .env.prod
- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-prod.yml
#100 에서 빼먹었네요~!
엔드포인트 어차피 브라우저 보면 나오는 건데 굳이 숨길 거 있나 싶어서, secret 대신 `.env.dev` 와 `.env.prod` 에 넣었습니다.
`dev` `prod` 는 제가 임의로 정한 단어입니다. (`deploy-dev` 와 `deploy-prod` 에서 따옴)
> :adhesive_bandage: env 변경에 따른 CI 스크립트 수정

- src/pageImpl/searchImpl/__components__/Searchbar.tsx
> :adhesive_bandage: 검색 인풋 리액트 경고 픽스

- .eslintrc
- src/pageImpl/detailImpl/__components__/EvaluationModifySheet.tsx
- src/pageImpl/detailImpl/__components__/LectureReviewCard.tsx
- src/pageImpl/detailImpl/index.tsx
- src/pageImpl/mailVerifyImpl/index.tsx
- src/pageImpl/mainImpl/index.tsx
- src/pageImpl/recentImpl/index.tsx
- src/pageImpl/searchImpl/__components__/Searchbar.tsx
- src/pages/_app.tsx
Fragment 를 안 쓸 수 있다면 굳이 쓸 이유가 없어서, 해당 규칙을 추가합니다.
> :art: setup eslint no-useless-fragment

- src/lib/dto/core/mainEvaluation.ts
- src/lib/dto/getMainTagEvaluations.ts
- src/lib/util/env.ts
- src/mocks/handlers/core/index.ts
- src/mocks/handlers/ev/fixtures.ts
- src/mocks/handlers/ev/index.ts
- src/pages/_app.tsx
> :clown_face: msw 환경 integration & main 페이지에 msw 적용

- src/lib/dto/core/evaluation.ts
- src/lib/dto/core/user.ts
- src/lib/dto/postEvaluation.ts
- src/lib/dto/postReportEvaluation.ts
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1663509125822879?thread_ts=1663401847.494509&cid=C0PAVPS5T
> :label: user type 엄밀하게 체크

- src/lib/dto/core/tag.ts
- src/lib/dto/core/tagGroup.ts
- src/pageImpl/searchImpl/__components__/SelectedTagList.tsx
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1663405365868979?thread_ts=1663401847.494509&cid=C0PAVPS5T
> :label: color type string | null 로 처리

- playwright.config.ts
자꾸 원래 run 하던 서버 끄고 해야 되는 거 짜증나서
> 🧑‍💻 playwright port 커스텀 가능하게 & default 3001 로 변경

- src/pages/_app.tsx
웹뷰라 개발자만 귀찮고 아무 의미 없는 옵션이 되어 off
> 🧑‍💻 refetchonwindowrefocus 옵션 끄기

- e2e/main/evaluations.spec.ts
- e2e/main/header.spec.ts
- e2e/main/recent.spec.ts
- e2e/main/tag.spec.ts
- next.config.js
> :truck: trailing slash 옵션 off

- e2e/main/evaluations.spec.ts
- e2e/main/header.spec.ts
- e2e/main/recent.spec.ts
- e2e/main/tag.spec.ts
- next.config.js
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1663690878281909?thread_ts=1663686803.191739&cid=C0PAVPS5T
> 🚑 trailing slash 옵션 true 로 롤백

- .github/workflows/build.yml
- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-prod.yml
- .github/workflows/playwright.yml
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1663590319913069
> :boom: base branch main 으로 변경, tag-base deployment 로 변경

- README.md
- package.json
- scripts/deploy.sh
https://user-images.githubusercontent.com/39977696/191633443-ddbc4bfd-f253-4be2-939c-a2bc27cf6a19.mov
> :technologist: tag 생성하여 푸시하는 스크립트 생성

- README.md
- package.json
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1663826219977309?thread_ts=1663807160.471539&cid=C0PAVPS5T
> :fire: 불필요한 script 셋업 제거

- src/lib/styles/fonts.ts
> :zap: 디폴트로 시스템 폰트 이용

- Dockerrun.aws.json
> :ambulance: dockerrun 에 image tag 오타 수정

- src/pages/500.tsx
> :beers: custom 500 페이지 Appbar 수정사항 반영 안돼서 추가

- src/lib/components/CollapsableText/index.tsx
- src/pageImpl/recentImpl/__components__/RecentResultItem.tsx
- src/pageImpl/searchImpl/__components__/SearchOptionSheet/TagItem.tsx
- src/pageImpl/searchImpl/__components__/SearchOptionSheet/TagList.tsx
> :recycle: FC 제거

- .prettierrc
- e2e/recent/lecture-list.spec.ts
- src/pageImpl/recentImpl/__components__/RecentResultItem.tsx
- src/pageImpl/recentImpl/__containers__/useLatestLectures.ts
- src/pageImpl/recentImpl/index.tsx
최근 목록 갈아엎었습니다.
prettier printwidth 120으로 늘렸습니다.
> ✨ 최근 학기 강의 목록 재구현

- Dockerfile
> 🚑 dev 터진 것 핫픽스

- src/pageImpl/mainImpl/index.tsx
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1664106998041699?thread_ts=1664094668.310329&cid=C0PAVPS5T
> 🩹 강의평 없으면 0 뜨는 버그 픽스

- src/pages/_app.tsx
https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-tap-highlight-color
https://gahyun-web-diary.tistory.com/77
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1664094668310329
> 💄 tab 했을 때 파란색 하이라이트 색 제거

- src/pages/_app.tsx
> 💄 input 테두리 파란색 제거

- src/pageImpl/createImpl/__components__/EvalPolygon.tsx
> 🩹 evalPolygon 터치 시 주변에 뭐 뜨는거 픽스

- src/usecases/lecture/formatLecturesToYearSemesterLectures.test.ts
- src/usecases/lecture/formatLecturesToYearSemesterLectures.ts
> 🧪 강좌를 학년 학기 순으로 포매팅하는 함수 단위 테스트 추가

- src/entities/lecture.ts
- src/lib/util/index.ts
- src/pageImpl/recentImpl/__containers__/useLatestLectures.ts
- src/pageImpl/recentImpl/index.tsx
- src/usecases/lecture/formatLatestLectureToYearSemester/index.test.ts
- src/usecases/lecture/formatLatestLectureToYearSemester/index.ts
- src/usecases/lecture/semesterToString/index.ts
entity 인가 usecase 인가에 대한 고민을 했다가, [이거](https://wafflestudio.slack.com/archives/C0PAVPS5T/p1663594727214279?thread_ts=1663594373.791789&cid=C0PAVPS5T) 보고 엔티티 레벨보다는 좀더 유동적이어야겠다고 생각해서 usecase 로 넣었습니다.
> 🏗️ semesterToString usecase 생성

- scripts/deploy.sh
> 🧑‍💻 배포 스크립트 tag 두껍게

- README.md
- package.json
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1664188756583149
> 🚚 snutt-ev-web 으로 rename

- README.md
- src/clients/axiosCoreClient.ts
- src/clients/axiosEvClient.ts
괜히 관리 포인트만 늘어나는 것 같아서 환경변수에서 토큰 가져오는 로직 없앴습니다.
> 🧱 토큰 셋업 로직을 쿠키로만 가능하게 변경

- e2e/detail/_page.ts
- e2e/detail/evaluations.spec.ts
- src/lib/components/Icons/SvgMaximize.tsx
- src/lib/dto/evaluation.ts
- src/mocks/handlers/ev/index.ts
- src/pageImpl/detailImpl/__components__/DeleteEvaluationDialog.tsx
- src/pageImpl/detailImpl/__components__/DetailAppBar.tsx
- src/pageImpl/detailImpl/__components__/EvaluationDetailScore.tsx
- src/pageImpl/detailImpl/__components__/EvaluationScoreDialog.tsx
- src/pageImpl/detailImpl/__components__/LectureReviewCard.tsx
- src/pageImpl/detailImpl/__components__/ReportEvaluationDialog.tsx
- src/pageImpl/detailImpl/index.tsx
> ✨ 상세 점수 팝업 구현

- src/pageImpl/detailImpl/__queries__/index.ts
- src/pageImpl/detailImpl/index.tsx
- src/pages/detail/index.tsx
resolves https://wafflestudio.slack.com/archives/C8M9NUBBR/p1664760207292299
> 🚸 detail page full ssr 적용

- e2e/me/evaluations/evaluations.spec.ts
- src/lib/styles/colors.ts
- src/pageImpl/myEvaluationsImpl/__components__/MyEvaluationsAppBar.tsx
- src/pageImpl/myEvaluationsImpl/index.tsx
- src/pages/me/evaluations.tsx
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1664781126226629?thread_ts=1664613002.779849&cid=C0PAVPS5T
> ✨ 내가 쓴 강의평 개수 보여주기

- .github/workflows/deploy-prod.yml
> 🧑‍💻 prod 배포 슬랙 노티 메세지 관련 수정

- src/pageImpl/detailImpl/__components__/LectureReviewCard.tsx
> :tada: 강의평 상세점수 prod 배포

- src/pageImpl/mainImpl/index.tsx
> :tada: 내 강의평 모아보기 기능 피쳐플래그 제거하여 prod 배포

- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-prod.yml
- Dockerfile
- src/@types/global.d.ts
- src/pages/_app.tsx
배포 버전을 더 잘 확인하기 위해, window 에 git hash 를 심습니다.
> 🧑‍💻 배포 시 window 에 git hash 심기

- src/pageImpl/mainImpl/__containers__/useSelectTag.ts
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1667042788885819
> 🩹 tag Id 에 NaN 들어가지 않도록 가드 추가

- src/pageImpl/detailImpl/__components__/ReportEvaluationDialog.tsx
from slack https://wafflestudio.slack.com/archives/C0PAVPS5T/p1667724491842399?thread_ts=1667724183.074759&cid=C0PAVPS5T
> 🚸 신고 내용 작성하지 않으면 신고 기능 disable

- .github/workflows/playwright.yml
resolves task https://www.notion.so/wafflestudio/playwright-e2e-ec1f6deee13b4a64b9cf287b3d27947b
> ⚒️ github workflow 와 package.json playwright 버전 통일

- .github/pull_request_template.md
PR 템플릿을 추가합니다.
👍 
- [kanban](https://www.notion.so/wafflestudio/PR-992c2b1307b946959968ce8834d98218)
> 📝 PR 템플릿 추가

- src/lib/apis/ev/index.ts
resolves #234 
- [kanban](https://www.notion.so/wafflestudio/affe9f1330174c04a75c31bd52ba54a3)
> 🎉 메인 페이지 prod 에서도 최근에 들은 강의 필터 파라미터 보내기

- src/lib/components/Appbar/BackButton.tsx
- src/lib/components/Appbar/index.tsx
- src/pageImpl/createImpl/index.tsx
- src/pageImpl/detailImpl/__components__/DetailAppBar.tsx
- src/pageImpl/mailVerifyImpl/index.tsx
- src/pageImpl/mainImpl/__components__/MainAppBar.tsx
- src/pageImpl/myEvaluationsImpl/__components__/MyEvaluationsAppBar.tsx
- src/pageImpl/recentImpl/index.tsx
- src/pageImpl/searchImpl/__components__/Searchbar.tsx
- src/pages/404.tsx
- src/pages/500.tsx
앱바 사용성을 높입니다.
- [kanban](https://www.notion.so/wafflestudio/AppBar-8f74cf1acf83493eb3deee1d6ddd9c80)
> ♻️ 앱바 사용성 개선을 위한 리팩토링

- src/@types/emotion.d.ts
- src/lib/components/Button/index.tsx
- src/lib/styles/colors.ts
- src/lib/styles/theme.ts
- src/pageImpl/createImpl/index.tsx
- src/pageImpl/mailVerifyImpl/index.tsx
- [kanban](https://www.notion.so/wafflestudio/69a16784363b4357a83617041ae81b9c)
> 💄 이메일 인증 페이지 & CTA버튼 다크모드 적용

- src/@types/emotion.d.ts
- src/lib/styles/colors.ts
- src/lib/styles/theme.ts
- src/pageImpl/mainImpl/__components__/RecentCarousel.tsx
- src/pageImpl/recentImpl/__components__/RecentResultItem.tsx
- src/pageImpl/recentImpl/index.tsx
- [kanban](https://www.notion.so/wafflestudio/69a16784363b4357a83617041ae81b9c)
> 💄 영역 divider 다크모드 적용

- src/@types/emotion.d.ts
- src/lib/styles/theme.ts
- src/pageImpl/detailImpl/__components__/DeleteEvaluationDialog.tsx
- src/pageImpl/detailImpl/__components__/EvaluationScoreDialog.tsx
- src/pageImpl/detailImpl/__components__/ReportEvaluationDialog.tsx
- src/pageImpl/mainImpl/__components__/EvaluationCard.tsx
자세한 건 커밋
- [kanban](https://www.notion.so/wafflestudio/69a16784363b4357a83617041ae81b9c)
> 💄 dialog 에 다크모드 적용

- .eslintrc
- src/lib/components/atoms/CircularLoader.tsx
- src/lib/components/molecules/LoadingIndicator.tsx
- src/pageImpl/detailImpl/index.tsx
- src/pageImpl/mainImpl/index.tsx
- src/pageImpl/myEvaluationsImpl/index.tsx
- src/pageImpl/searchImpl/index.tsx
눈으로 보고 베껴서 똑같이 만들었습니다.
https://github.com/mui/material-ui/blob/master/packages/mui-material/src/CircularProgress/CircularProgress.js
번들도 꽤 줄었습니다. (1 / 1 / 5 / 5kb)
- 기존
- 개선 이후
- [kanban](https://www.notion.so/wafflestudio/mui-circularprogress-d057e2bf532246a7afa884f1a25a83aa)
> ♻️ CircularProgress 의존성 제거

- src/pageImpl/detailImpl/__components__/EvaluationDetailScore.tsx
0.2kb 줄었습니다.
- 기존
- 개선 이후
- [kanban](https://www.notion.so/wafflestudio/mui-Box-be05c67190224f309701ddcf422685ac)
> ♻️ mui Box 의존성 제거

- src/lib/components/atoms/Chip.tsx
- src/pageImpl/mainImpl/index.tsx
10kb 정도 줄였습니다.
- 기존
- 개선 이후
- [kanban](https://www.notion.so/wafflestudio/mui-ToggleButton-e5599c0352db4f41afb5f63e18feef9d)
> ♻️ mui ToggleButton 의존성 제거

- src/lib/components/atoms/Backdrop.tsx
- src/lib/components/organisms/Portal.tsx
- src/lib/components/templates/Dialog.tsx
- src/pageImpl/createImpl/index.tsx
- src/pageImpl/detailImpl/__components__/DeleteEvaluationDialog.tsx
- src/pageImpl/detailImpl/__components__/EvaluationScoreDialog.tsx
- src/pageImpl/detailImpl/__components__/ReportEvaluationDialog.tsx
- src/pageImpl/detailImpl/index.tsx
- src/pages/_document.tsx
각 14kb 14kb 1kb 줄였습니다.
- 기존
- 개선 이후
- [kanban](https://www.notion.so/wafflestudio/mui-Dialog-8190abcb90c84305ba76e97d1ed15715)
> ♻️ mui dialog 의존성 제거

- src/lib/features/flags.ts
- src/pageImpl/detailImpl/__components__/LectureReviewCard.tsx
- src/pageImpl/mainImpl/__components__/EvaluationCard.tsx
- src/pageImpl/myEvaluationsImpl/__components__/MyEvaluationCard.tsx
서버가 prod 까지 나간 관계로 피쳐플래그 제거하고 prod 보냅니다.
머지하고 릴리즈따면 공감기능 prod 배포됩니다.
- [kanban](https://www.notion.so/wafflestudio/b46750db746244f0b3b3656838a40e76)
> 🎉 강의평 공감 기능 웹뷰 피쳐플래그 제거

- src/lib/components/atoms/LikeButton.tsx
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1669957635758509?thread_ts=1668299933.853369&cid=C0PAVPS5T
리베이스하다가 꼬였나봅니다
> 🚑 강의평 따봉한거 안보이는거 핫픽스

- e2e/detail/_page.ts
- e2e/detail/onBackClose.spec.ts
- src/lib/components/atoms/AppBarBackButton.tsx
- src/lib/components/atoms/AppBarCloseButton.tsx
- src/lib/components/molecules/AppBar.tsx
- src/lib/util/withGetServersideProps.ts
- src/pageImpl/detailImpl/__components__/DetailAppBar.tsx
- src/pageImpl/detailImpl/index.tsx
- src/pages/detail/index.tsx
`on_back=close` 로 들어오면 close 버튼을 띄웁니다. 브릿지는 아직 미구현입니다.
- [kanban](https://www.notion.so/wafflestudio/7fb7e89a74b2498da659aea7c56952bd)
> ✨ 강의평 상세 페이지 쿼리파람이 on_back=close 이면 닫기버튼 호출

- src/lib/components/atoms/AppBarCloseButton.tsx
- src/lib/contexts/nativeBridge.tsx
- src/pages/_app.tsx
- src/pages/_document.tsx
- [kanban](https://www.notion.so/wafflestudio/d291fe606ec0407ea1292120b070db90)
> ✨ 브릿지 호출을 위한 context 밑작업

- e2e/detail/onBackClose.spec.ts
- src/lib/contexts/nativeBridge.tsx
- src/lib/contexts/nativeDevice.tsx
- src/mocks/handlers/ev/index.ts
- src/pages/_app.tsx
- src/pages/_document.tsx
- [kanban](https://www.notion.so/wafflestudio/d291fe606ec0407ea1292120b070db90)
- slack: https://wafflestudio.slack.com/archives/C0PAVPS5T/p1670082082551769
> ✨ 브릿지 호출을 위한 device type 밑작업

- src/lib/components/atoms/LikeButton.tsx
> 💄 likeButton 클릭 시 딤처리

- e2e/verify/failure.spec.ts
- src/mocks/handlers/core/index.ts
- src/pageImpl/mailVerifyImpl/index.tsx
fixes https://wafflestudio.slack.com/archives/C0PAVPS5T/p1670651326554009
누가 if문을 저렇게 써놓습니다
> 🚑 이메일 인증코드 요청 시 request errormessage 오류 수정

- src/pageImpl/mainImpl/__components__/RecentCarousel.tsx
- src/pageImpl/mainImpl/index.tsx
- src/styles/global.tsx
- [kanban](https://www.notion.so/wafflestudio/417e37c3b0104743b9a180756d6c93fc)
> 🚸 롱클릭 액션들 방지

- e2e/detail/onBackClose.spec.ts
- src/@types/global.d.ts
- src/contexts/nativeBridge.tsx
playwright 가 window 에 심어둔 함수를 spy하는 기능을 지원을 안하나?
- [kanban](https://www.notion.so/wafflestudio/X-b86336aefbd04b90b41812229212a021)
> ✨ X버튼 클릭 시 웹뷰 종료 브릿지 호출

- e2e/detail/evaluations.spec.ts
- src/components/atoms/LikeButton.tsx
- src/pageImpl/detailImpl/__components__/LectureReviewCard.tsx
- src/pageImpl/detailImpl/index.tsx
- src/pageImpl/mainImpl/__components__/EvaluationCard.tsx
- src/pageImpl/myEvaluationsImpl/__components__/MyEvaluationCard.tsx
- src/utils/getOptimisticLikeButton.ts
https://wafflestudio.slack.com/archives/C8M9NUBBR/p1671077926359749
이거도 같이 고칩니다.
- [kanban](https://www.notion.so/wafflestudio/optimistic-ui-77b9a730ba7b457a8a96cee7003b5216)
> 🚸 강의 상세 페이지 좋아요 버튼에 optimistic update 적용 & 내 강의평 좋아요 여부 업데이트 안되는 버그 픽스

- src/contexts/nativeBridge.tsx
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1671324752396979?thread_ts=1671295855.644049&cid=C0PAVPS5T
try-catch 문으로 일단 감쌉니다.
> 🩹 add guard to postMessage call

- .env.dev
- .env.prod
- [kanban](https://www.notion.so/wafflestudio/serverside-internal-endpoint-382b6521d2964da484daa7a7f1070ef5)
> 👽 배포환경 서버사이드 요청들 internal endpoint 로 변경

- src/pageImpl/detailImpl/__components__/LectureReviewCard.tsx
- src/pageImpl/mainImpl/__components__/EvaluationCard.tsx
- src/pageImpl/mainImpl/index.tsx
- [kanban](https://www.notion.so/wafflestudio/optimistic-ui-77b9a730ba7b457a8a96cee7003b5216)
> 🚸 메인 화면 강의평 좋아요 버튼에 optimistic update 적용

- src/pageImpl/myEvaluationsImpl/__components__/MyEvaluationCard.tsx
- [kanban](https://www.notion.so/wafflestudio/optimistic-ui-77b9a730ba7b457a8a96cee7003b5216)
> 🚸 내 강의평 목록 페이지 optimistic update 적용

- e2e/detail/evaluations.spec.ts
- e2e/detail/report.spec.ts
- src/mocks/handlers/ev/index.ts
- src/pageImpl/detailImpl/__components__/EvaluationModifySheet.tsx
- src/pageImpl/detailImpl/__components__/LectureReviewCard.tsx
- src/pageImpl/detailImpl/__components__/ReportEvaluationDialog.tsx
- [kanban](https://www.notion.so/wafflestudio/17368650d1c14d81b626dda11516f33c)
> 🩹 강의평 신고 후 다른 강의평 또 신고하려고 하면 이전에 신고한 내용 그대로 남아있는 버그 픽스

- src/pageImpl/searchImpl/__components__/SearchOptionSheet/index.tsx
근본적인 픽스는 인프라에서 해줘야 합니다.
이슈: https://wafflestudio.slack.com/archives/C0PAVPS5T/p1672488481480329
> 🩹 ssr 오류 시 tagGroup 선택 안되는 현상 가드

- next.config.js
resolves task https://www.notion.so/wafflestudio/5ff82faa5e744ab187eb7a724159ae97
experimental 인데 왠지 잘 동작합니다.
> 🚸 scroll restoration

- src/pageImpl/mainImpl/index.tsx
- src/pages/main/index.tsx
- src/truffle/index.ts
https://wafflestudio.slack.com/archives/C04HQSVCH39/p1674394932655529
추후 truffle sdk 로 분리될 예정입니다.
> ✨ truffle client 생성

- src/truffle/index.ts
> 🚧  truffle elements js에 맞게 픽스

- src/utils/withGetServersideProps.ts
> 🚧 withGetServerSideProps 에서 에러 캡쳐, unknown string 개선

- .github/workflows/build.yml
- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-prod.yml
- .github/workflows/jest.yml
- .github/workflows/playwright.yml
- Dockerfile
- src/@types/global.d.ts
- src/pages/_app.tsx
> ⬆️ github actions v3 으로 업그레이드

- src/components/atoms/LikeButton.tsx
- src/components/organisms/CollapsableText.tsx
- src/pageImpl/mainImpl/__components__/EvaluationCard.tsx
- src/pageImpl/myEvaluationsImpl/__components__/MyEvaluationCard.tsx
resolves https://wafflestudio.slack.com/archives/C8M9NUBBR/p1674908149510979
resolves https://www.notion.so/wafflestudio/emotion-styled-react-dom-unknown-property-aa7003e9428d4154a9b01df157d8e6f7
> 🚸 강의평 카드 클릭 시 내 강의평으로 넘어가는 클릭 영역 확대

- src/pages/_app.tsx
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1675007677638799?thread_ts=1673436263.985449&cid=C0PAVPS5T
이슈 있으면 바로 롤백할 수 있어야 해서, 노머지 배포합니다.
> 🚧 ios 면 window.history.scrollRestoration 을 auto 로 변경

- src/contexts/nativeBridge.tsx
- src/contexts/nativeDevice.tsx
- src/utils/withGetServersideProps.ts
context: https://wafflestudio.slack.com/archives/C0PAVPS5T/p1675421238754339?thread_ts=1674916329.241239&cid=C0PAVPS5T
> 👽 트러플에 os type, app version 추가

- src/utils/withGetServersideProps.ts
> ✨ 쿠키 전체를 truffle 에 쏘기

- src/pageImpl/createImpl/CreateImpl.tsx
- src/pageImpl/mainImpl/index.tsx
> 강의평 등록 시 따닥 이슈 제거

- src/pageImpl/mailVerifyImpl/MailVerifyGuide/index.tsx
- src/pageImpl/mailVerifyImpl/index.tsx
이미 사용한 이메일로 인증 시도 시, 메시지 추가
- [kanban]()
> 이미 사용한 이메일로 인증 시도 시, 메시지 추가

- src/@types/emotion.d.ts
- src/pageImpl/mailVerifyImpl/MailVerifyGuide/index.tsx
- src/pageImpl/mailVerifyImpl/index.tsx
- src/styles/theme.ts
> 이메일 안내문구 다크모드 대응

- src/hooks/useOutsideClick.ts
- src/pageImpl/createImpl/CreateHeader/index.tsx
- 학기 선택 selectBox 외부 클릭 시 닫히도록 개선
> 학기 선택 selectBox 외부 클릭 시 닫히도록 개선

- src/utils/withGetServersideProps.ts
- 이메일 인증 확인 시, 이후에는 페이지 이동 시 이메일 인증 스킵
> 이메일 인증 확인 시, 이후에는 페이지 이동 시 이메일 인증 스킵

- .github/workflows/deploy-prod.yml
> 🩹 fix title

- .github/workflows/deploy-prod.yml
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1707061116001799
> 🔥 slack notify step 제거

- .env.dev
- .env.prod
> server_side api url 변경

- src/pageImpl/createImpl/CreateImpl.tsx
> 수강학기 없을 경우 다음 버튼 disabled
