wafflestudio/snutt-ev-web

- lib/api/apis.ts
- lib/components/Text/Detail.ts
- lib/dto/review.ts
- lib/styles/colors.ts
- pageImpl/mainImpl/__components__/ReviewCard.tsx
- pageImpl/mainImpl/__containers__/index.ts
- pageImpl/mainImpl/index.tsx
- pages/main/index.tsx
- /main 에 들어갈 메인 페이지 컴포넌트 생성
- main review mock 데이터 생성
- main page 아랫 부분(리뷰 큐레이션)에 들어갈 카드뷰 생성
TODO : 별은 다른 PR로 만들게요
- react-query를 통해 api fetch를 하면 세 상태(data, isLoading, error)를 얻을 수 있는데, isLoading, error를 처리하는 방법으로 React Suspense를 도입하면 어떨까 해요. 컨테이너마다 error, loading 상태에 대한 처리를 매번 해주지 않고 하나의 Provider 로 감싸서 처리해줄 수 있다고 합니다. 
관련 자료로, https://ko.reactjs.org/docs/concurrent-mode-suspense.html, https://react-query.tanstack.com/guides/suspense
- /pages 에서 각 페이지는 /pages/{이름}/index.tsx 로, 디렉토리로 분류하면 좋을 것 같습니다.
그리고 현재 mock api를 사용해서 컴포넌트를 테스트하고 있는데, mock을 이용해 테스트 코드도 만들어보면 어떨지 생각중
`/main`
> Main Page 강의평 큐레이션 카드 뷰 (SNUTT-233)

- .env.production
Dev 배포 위해 임시로 url 변경. 이건 main으로 바로 머지 되지는 않을 것. .env 파일을 github secret으로 넣어야겠다
> temp dev api url as prod

- lib/components/CollapsableText/index.tsx
api 응답으로는 `"강의평 첫줄 \n 강의평 둘째 줄" `이렇게 `'\n'`이 포함된 스트링으로 오는데, 이걸 `review.content`와 같은 방식으로 object 안으로 들어가면
```
'강의평 첫줄
강의평 둘째 줄'
```
이런 식으로 \n이 (console.log 상에서) 사라진 string으로 형태가 달라지네요. 근데 이때도 `content.find('\n')` 같이 \n 검색하며 나오긴 합니다. 뭔가 오묘한 string, new line, escape string 로직에 의한 이슈인 것 같은데 정확한 원인은 모르겠어요
위와 같이 \n이 없는 new line string 형태일 때 CSS whitespace 속성으로 new line 적용이 가능하네요. `pre-wrap`은 tab과 new line을 적용한다는 뜻입니다. [링크](https://stackoverflow.com/questions/39325414/line-break-in-html-with-n)
> [SNUTT-388] newline 이슈

- .eslintrc
- package.json
- yarn.lock
@typescript-eslint 를 셋업합니다. [(docs)](https://typescript-eslint.io)
이를 통해 타입스크립트에 더 알맞는 린트 설정을 가질 수 있도록 합니다.
린트 에러가 좀 터졌는데, 중요한 에러들로는 `no-var` 이 보였고 고치면 좋을 친구들로는 `ban-types` 가 보였습니다. 일단 고치지 않고 모두 warn 으로 우회만 했습니다! 추후 고쳐야 할 포인트라고 보여 TODO 처리했습니다.
`no-empty-interface`는 개인 취향에 따라 코드 퀄리티를 해치치 않는데 굳이굳이 금지하는 투머치 규칙이라고 생각되어 off했습니다.
린트 설정만 바꾼거라 프로덕션에는 영향이 갈 수 없습니다.
> 🧑‍💻 setup typescript-eslint & set error as warning

- .github/workflows/build.yml
깃헙액션에서 CI 돌도록 합니다.
zero-install 하면 아예 스크립트 가르는게 나을지도? build 랑 lint 랑 (나중에 테스트코드 추가하면 test 도)
> :construction_worker: add lint check with github action

- .eslintrc
- lib/hooks/useScrollLoader.ts
`{}` 는 타입으로 활용하지 않습니다.
해당 함수의 경우 훅에서 받아서 파라미터도 넘기지 않고 리턴값도 쓰지 않기 때문에, `() => void` 가 적절한 타입이라고 판단했습니다.
> :rotating_light: ban-types 린트 옵션 켜기

- README.md
- lib/api/request.ts
[컨텍스트](https://wafflestudio.slack.com/archives/C0PAVPS5T/p1662895399569399)
일단 client 생성해뒀고, 하나씩 하나씩 저걸로 마이그레이션하려고 합니다.
기존의 `SnuttAPI`는 deprecate했습니다.
```env
NEXT_PUBLIC_CORE_API_URL=https://snutt-api-dev.wafflestudio.com
NEXT_PUBLIC_EV_API_URL=https://snutt-api-dev.wafflestudio.com/ev-service
```
이거 두개 github secret 에 등록해야 합니다.
> :building_construction: api client 생성

- .eslintrc
- lib/hooks/useScrollLoader.ts
- pages/_app.tsx
최근들어 exhausitive-deps 옵션의 중요성을 더더 깨닫고 있어서, error 로 설정하고 기존 에러들은 픽스합니다.
`useScrollLoader.ts` 의 경우 `useCallback` 자체가 아무 의미 없기 때문에 그냥 제거했습니다.
`_app.ts` 의 경우 함수를 이펙트 안에서 선언하여 dependency 를 해결합니다. 해결하는 김에 로직 좀더 간단하게 쓸 수 있을 거 같아서 수정했습니다.
> 🧑‍💻 exhaustive-deps 옵션 error 로 설정

- .env.dev
- .env.prod
- .env.test
- README.md
- package.json
- src/lib/util/env.ts
test 환경은 계속 고도화해야 합니다. 장기적으로는 test 로 오픈 시 msw 로 켜져야 합니다.
`yarn dev:test` 로 켜면 test 환경으로 오픈되는데, 현재는 api 모킹이 덜 되어 있는 관계로 시원하게 터집니다.
> :bricks: app-env 로 local dev prod test 환경 명시

- src/pageImpl/searchImpl/__components__/SearchOptionSheet/TagList.tsx
- src/pageImpl/searchImpl/__components__/SearchOptionSheet/index.tsx
- src/pageImpl/searchImpl/__components__/Searchbar.tsx
- src/pageImpl/searchImpl/__components__/SelectedTagList.tsx
- src/pageImpl/searchImpl/__containers__/useSearchOptions.ts
- src/pageImpl/searchImpl/__containers__/useSearchResult.ts
- src/pageImpl/searchImpl/index.tsx
- selectedTag 목록을 tag 전체 정보를 저장하고 있었는데, id만 저장하도록 변경했습니다.
- 검색어 초기값을 `''` 로 변경하여, 검색어도 태그도 없는 상태에서 검색 눌렀을 때 전체 쿼리로 검색되는 버그를 픽스했습니다.
> ♻️ search page 리팩토링 & 검색어 없으면 쿼리 안 쏘도록 변경

- src/pageImpl/searchImpl/__components__/Searchbar.tsx
- src/pageImpl/searchImpl/__containers__/useSearchOptions.ts
- src/pageImpl/searchImpl/__containers__/useSearchTags.ts
검색 정보를 url에 저장하여, 어디 갔다가 돌아와도 검색 결과가 유지됩니다. 페이지네이션 결과는 유지 안되는데 그건 어쩔 수 없는 걸로 아는데 추후 개선사항으로 생각해 보겠습니다.
[src/pageImpl/searchImpl/__containers__/useSearchOptions.ts](https://github.com/wafflestudio/SNUTT-web/pull/148/files#diff-6eb9deb96c11fc84cca8e41627f6f90112a8ba23eb8800fa9b36591c777e8809) 파일만 해당 PR과 유관하고, 나머지는 그냥 마이너 개선사항인데 실수로 커밋을 합쳐버렸습니다.
https://user-images.githubusercontent.com/39977696/190915346-ea863604-f157-4783-9d2c-82f94726e357.mov
> 🚸 검색 후 어디 갔다가 돌아오면 검색 풀리는 현상 개선

- src/pages/500.tsx
500 상황에서 기존에는 Next.js 기본 500 페이지가 보였는데, 아무래도 커스텀 페이지를 띄워주는 게 그래도 좋을 것 같아서 추가합니다.
별개로 이 페이지가 보였으면 슬랙 노티를 보내는 등의 작업도 되면 좋을 것 같습니다.
> 🚸 custom 500 페이지 추가

- .github/workflows/deploy-dev.yml
wafflestudio/snutt-ev#60, wafflestudio/snutt#224 와 같은 변경.
[ecr-image-tag-updater](https://github.com/wafflestudio/ecr-image-tag-updater)를 이용해 wafflestudio-cluster 에 자동 배포
1. GitHub Actions (in each repo) build and push docker image to ECR
2. ECR push event triggers AWS Lambda function
3. This Lambda function updates the image tag of the corresponding manifest file in [waffle-world](https://github.com/wafflestudio/waffle-world)
4. ArgoCD detects the change in the manifest file and deploys the new image
(ECR 에 untagged image 삭제하는 건, ECR 자체 lifecycle policy 설정으로 5개 초과해서 이미지 저장되면 오래된 것부터 지우게 설정해두어서 스크립트로 처리할 필요가 없어짐)
> ☸  dev 환경 wafflestudio-cluster 에 자동 배포 설정

- .env.dev
dev 환경은 server side 가 k8s cluster 에 존재하기에, 굳이 VPC 밖으로 나가지 않고 같이 cluster 내에 있는 snutt-ev 로 바로 요청 보내도록 변경
> :alien: Modify dev ev-server url of  server-side

- src/pageImpl/detailImpl/__components__/ReportEvaluationDialog.tsx
오늘 코드 보다가 생각해보니 dom과 리액트를 동기화하는 작업이 아니고 리액트 내부 동작이기 때문에 effect 훅 없이 핸들러에서 처리하는 게 맞을 것 같아서 핸들러에서 처리합니다.
> ♻️ 신고 모달 닫을 때 useEffect 대신 핸들러에서 내용 초기화

- e2e/detail/evaluations.spec.ts
- e2e/main/evaluations.spec.ts
- e2e/me/evaluations/evaluations.spec.ts
- playwright.config.ts
- src/lib/apis/ev/index.ts
- src/mocks/handlers/ev/index.ts
- src/pageImpl/detailImpl/__components__/LectureReviewCard.tsx
- src/pageImpl/detailImpl/index.tsx
- src/pageImpl/mainImpl/__components__/EvaluationCard.tsx
- src/pageImpl/mainImpl/index.tsx
- src/pageImpl/myEvaluationsImpl/__components__/MyEvaluationCard.tsx
강의평 좋아요 api를 실제로 쏘는 기능입니다.
테스트코드를 어떻게 짜야 할지 고민했는데, post request 쏘고 refetch get request 쏘고 invalidate api 쏘는 거 정도만 테스팅하면 되겠죠..? playwright 에서 테스트 러닝 중에 쿠키를 건드릴 수가 없다 보니 msw 에서 쏜 결과가 반영되는 것까지 테스트하는 건 불가능할 것 같긴 한데 아이디어 있으시면 도와주시면 매우 감사드리겠습니다!
---
- 강의평 좋아요 / 좋아요 취소 api 추가 및 클릭 시 api 쏘는 기능 구현
- 좋아요 눌렀을 때 request 랑 response 테스트하는 테스트코드 추가
- 강의평 테스트코드 파일 TC에서 좋아요 기능 테스트하는 step 을 따로 분리
- playwright 에 `wait` 하는 케이스가 추가되었는데, 이게 config 에서 30초로 걸려 있어서 30초동안 기다려보고 안오면 터트림. 다시 말해서 10번 실패하면 5분동안 테스트 fail 하는 거 붙들고 있는 건가? 싶어서.. 30초 -> 10초 로 줄였습니다 (사실 5초로 줄여도 될듯)
> ✨  강의평 공감 기능 (2): 강의평 좋아요 api 쏘는 기능 구현

- src/lib/styles/fonts.ts
iOS에서 폰트 로딩 속도 개선이 가능하지 않을까 싶습니다.
-apple-system 이 있으면 그걸 먼저 씁니다. 될진 모르겠습니다.
테스트 배포 먼저 나가겠습니다.
- [kanban](https://www.notion.so/wafflestudio/7683d9718d2f4a73a84650569f91c896)
- [slack](https://wafflestudio.slack.com/archives/C0PAVPS5T/p1668917860804159)
> ⚡ -apple-system 이 있으면 로컬 폰트 쓰도록

- src/lib/components/atoms/Input.tsx
- src/pageImpl/detailImpl/__components__/ReportEvaluationDialog.tsx
번들 사이즈 16~17kb 감소
- 기존
- 개선 이후
- [kanban](https://www.notion.so/wafflestudio/mui-TextField-359c17a8880c4a1d9ecb19b4902edb20)
> ♻️ mui TextField 의존성 제거

- src/lib/components/RatingGraph/index.tsx
- src/pageImpl/createImpl/__components__/EvalPolygon.tsx
- src/pageImpl/createImpl/__containers__/usePolygon.ts
- src/pageImpl/createImpl/index.tsx
- src/pageImpl/detailImpl/__components__/EvaluationDetailScore.tsx
mui slider 대신 input type=range 이용합니다. 7kb 정도 줄였습니다.
기존
개선 이후
- [kanban](https://www.notion.so/wafflestudio/mui-Slider-9857a4bacf2d4bdda29ee02bac9beb04)
> ♻️ mui Slider 의존성 제거

- .yarn/sdks/eslint/package.json
- .yarn/sdks/prettier/package.json
- src/mocks/handlers/ev/fixtures.ts
- src/pageImpl/mainImpl/index.tsx
fixes https://wafflestudio.slack.com/archives/C0PAVPS5T/p1671368132905159?thread_ts=1671269095.692439&cid=C0PAVPS5T
기존
변경
[caniuse gap?](https://caniuse.com/?search=gap)
> 🩹 태그 줄바꿈될 때 스타일 깨지는 이슈 픽스

- e2e/main/tag.spec.ts
- src/pageImpl/mainImpl/__containers__/useSelectTag.ts
- useSelectTag 불필요한 effect문 제거
- selectedTagId의 디폴트값 할당을 useEffect가 아닌 `||` 연산으로 해결
- [kanban](https://www.notion.so/wafflestudio/tag-effect-a4c1f14112eb46eaa42217e80144cc9e)
> ♻️ useSelectTag 불필요한 effect문 제거

- .env.dev
- .env.prod
applies https://wafflestudio.slack.com/archives/C0PAVPS5T/p1672672965403169?thread_ts=1672488481.480329&cid=C0PAVPS5T
ev 서버로 바로 찌르면 헤더가 없어서 오류납니다
> 👽 fix ev endpoint

- .github/workflows/deploy-prod.yml
> ♻️ 배포 알리미 ttuns 로 변경
